// <auto-generated />
using System;
using FMCGWebApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FMCGWebApplication.Migrations
{
    [DbContext(typeof(SystemDbContext))]
    [Migration("20250219132145_NewMigrationName")]
    partial class NewMigrationName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FMCGWebApplication.Models.Area", b =>
                {
                    b.Property<string>("AreaCode")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnOrder(1);

                    b.Property<short>("CompanyCode")
                        .HasColumnType("smallint")
                        .HasColumnOrder(0);

                    b.Property<string>("AreaGroup")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("EditLock")
                        .HasColumnType("bit");

                    b.Property<string>("Machine")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("PID")
                        .HasColumnType("int");

                    b.Property<int?>("hWnd")
                        .HasColumnType("int");

                    b.HasKey("AreaCode", "CompanyCode");

                    b.ToTable("TISAreaMst");
                });

            modelBuilder.Entity("FMCGWebApplication.Models.Company", b =>
                {
                    b.Property<short>("CompanyCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("CompanyCode"));

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusiType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CSTTinno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CST_No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EInvAuthExpTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fax")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LSTTinno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LST_No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PanNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone_Off")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone_Resi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone_STD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Www")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyCode");

                    b.ToTable("TISCompanyMst");
                });

            modelBuilder.Entity("FMCGWebApplication.Models.Groups", b =>
                {
                    b.Property<short>("CompanyCode")
                        .HasColumnType("smallint")
                        .HasColumnOrder(0);

                    b.Property<string>("GroupCode")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnOrder(1);

                    b.Property<byte?>("CrSeq")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("DrSeq")
                        .HasColumnType("tinyint");

                    b.Property<bool>("EditLock")
                        .HasColumnType("bit");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Machine")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PID")
                        .HasColumnType("int");

                    b.Property<string>("PTG")
                        .HasColumnType("nvarchar(1)");

                    b.Property<int?>("hWnd")
                        .HasColumnType("int");

                    b.HasKey("CompanyCode", "GroupCode");

                    b.ToTable("TISGroupMst", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
