// <auto-generated />
using System;
using FMCGWebApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FMCGWebApplication.Migrations
{
    [DbContext(typeof(SystemDbContext))]
    [Migration("20250222122201_statecreate")]
    partial class statecreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FMCGWebApplication.Models.Accounts", b =>
                {
                    b.Property<short>("CompanyCode")
                        .HasColumnType("smallint")
                        .HasColumnOrder(0);

                    b.Property<string>("GroupCode")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("AcCode")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnOrder(1);

                    b.Property<byte?>("ARAPStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("AcName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AcType")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AdharCardNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<byte?>("BillType")
                        .HasColumnType("tinyint");

                    b.Property<string>("CSTTINNO")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CST_No")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("CrAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<short?>("CrDays")
                        .HasColumnType("smallint");

                    b.Property<string>("CreditAbbrv")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("DebitAbbrv")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("EditLock")
                        .HasColumnType("bit");

                    b.Property<string>("FaxNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("GSTNO")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LSTTINNO")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LST_No")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LicNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Machine")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Mobil")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("OGS")
                        .HasColumnType("bit");

                    b.Property<string>("PANNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PID")
                        .HasColumnType("int");

                    b.Property<string>("PTG")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Phone_Off")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone_Resi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone_STD")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte?>("TrnType")
                        .HasColumnType("tinyint");

                    b.Property<string>("WWW")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("hWnd")
                        .HasColumnType("int");

                    b.HasKey("CompanyCode", "GroupCode", "AcCode");

                    b.ToTable("TISAccountMst", "dbo");
                });

            modelBuilder.Entity("FMCGWebApplication.Models.Area", b =>
                {
                    b.Property<short>("CompanyCode")
                        .HasColumnType("smallint")
                        .HasColumnOrder(0);

                    b.Property<string>("AreaCode")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnOrder(1);

                    b.Property<string>("AreaGroup")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("EditLock")
                        .HasColumnType("bit");

                    b.Property<string>("Machine")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("PID")
                        .HasColumnType("int");

                    b.Property<int?>("hWnd")
                        .HasColumnType("int");

                    b.HasKey("CompanyCode", "AreaCode");

                    b.ToTable("TISAreaMst");
                });

            modelBuilder.Entity("FMCGWebApplication.Models.Company", b =>
                {
                    b.Property<short>("CompanyCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("CompanyCode"));

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusiType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CSTTinno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CST_No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EInvAuthExpTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fax")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LSTTinno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LST_No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PanNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone_Off")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone_Resi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone_STD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Www")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyCode");

                    b.ToTable("TISCompanyMst");
                });

            modelBuilder.Entity("FMCGWebApplication.Models.Groups", b =>
                {
                    b.Property<short>("CompanyCode")
                        .HasColumnType("smallint")
                        .HasColumnOrder(0);

                    b.Property<string>("GroupCode")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnOrder(1);

                    b.Property<byte?>("CrSeq")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("DrSeq")
                        .HasColumnType("tinyint");

                    b.Property<bool>("EditLock")
                        .HasColumnType("bit");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Machine")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PID")
                        .HasColumnType("int");

                    b.Property<string>("PTG")
                        .HasColumnType("nvarchar(1)");

                    b.Property<int?>("hWnd")
                        .HasColumnType("int");

                    b.HasKey("CompanyCode", "GroupCode");

                    b.ToTable("TISGroupMst", "dbo");
                });

            modelBuilder.Entity("FMCGWebApplication.Models.States", b =>
                {
                    b.Property<string>("StateName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<short>("CountryId")
                        .HasColumnType("smallint");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("StateName");

                    b.ToTable("TISState", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
